name: Build Starsnin Browser

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar Repositório
      uses: actions/checkout@v4

    - name: Verificar Arquivos e Estrutura
      run: |
        echo "Verificando estrutura do navegador e o link do Starsnin..."
        ls -la

    - name: Compactar Artefatos do Projeto
      uses: actions/upload-artifact@v4
      with:
        name: starsnin-browser-files
        path: |
          *.html
          *.css
          *.js
          assets/
          *.png
          
