name: Build Starsnin Browser

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Repositorio
      uses: actions/checkout@v4

    - name: Gerar Artefato sem Modificar o Codigo
      uses: actions/upload-artifact@v4
      with:
        name: starsnin-browser-artifact
        path: .
        if-no-files-found: error
        
